version: '3.3'

services:
  mysql_server:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: Syst
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  java:
    container_name: walletServer
    image: openjdk:8
    ports:
      - "50051:50051"
    depends_on:
      - mysql_server
    volumes:
      - ./build/libs/grpc-java-hibernate-gradle-starter-server-1.0-SNAPSHOT.jar:/usr/local/grpc-java-hibernate-gradle-starter-server-1.0-SNAPSHOT.jar
    working_dir: /usr/local
    command: bash -c "java -jar grpc-java-hibernate-gradle-starter-server-1.0-SNAPSHOT.jar"